#!/usr/bin/python
#Title:         add_pyheader
#Author:        Luke Bechtel
#Description:   
#  Adds a generic python header to the file specified as argv[1]
#  WARNING: I'd recommend you only use this at the beginning 
#  of working on a file. Or only under version control. Just for safety's sake.

import sys
import os.path
import argparse
MY_TITLE = "Luke Bechtel (Marviel)"
BASIC_DESCRIPTION = "TODO"

parser = argparse.ArgumentParser(description=\
          "Adds a generic python header to the file specified as argv[1]")
parser.add_argument('modfile', type=argparse.FileType('r'))
parser.add_argument('--python3', action='store_true')
parser.add_argument('-t', '--title', type=str)
parser.add_argument('-a', '--authors', type=str, nargs='*')
parser.add_argument('-d', '--description', type=str)
args = parser.parse_args()

#Construct strings
modfile = args.modfile
filename = modfile.name
python_version_string = "python" + ("3" if args.python3 else "")
title_string = os.path.basename(filename) if not args.title else args.title
authors_string = ", ".join(args.authors) if args.authors else MY_TITLE
authors_plural = "s" if args.authors and len(args.authors) > 0 else ""
description_string = args.description if args.description else BASIC_DESCRIPTION

header = \
"""#!/usr/bin/%s 
#Title:      %s
#Author%s:     %s
#Description: 
#  %s
#

"""%(python_version_string,
     title_string,
     authors_plural,
     authors_string,
     description_string) 

data = modfile.read()
modfile.close()
with file(filename, 'w') as modified: modified.write(header + data)

